config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :user

  def vat_included_price
    self.price += price*0.18
  end

  # def vat_included_price=(price)
  #   self.price.to_f += price.to_f*0.18
  # end

  validates :title, presence:  true,  length: { minimum:  5, maximum:  30}
  validates :description, presence: true, length: {maximum: 300}
  validates :price, numericality: { greater_than_or_equal_to: 0}
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :products

  validates :username , presence: true, length: { minimum: 6, maximum: 20 }
  validates :email, presence:true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  validates :age, presence:  true, numericality: { greater_than: 15, only_integer: true}
  validates :city, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product.id)
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product.id)
    else
      render :edit
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to products_path
    else
      render inline: "İşlem başarısız"
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def delete
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :age, :city)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lyk2015Odev1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<% if @product.errors.any? %>
    <% @product.errors.full_messages.each do |msg| %>
        <%= msg %><br/>
    <% end  %>
<% end %>

<%= f.label :title %>
<%= f.text_field :title %>
<br/>
<%= f.label :description %>
<%= f.text_field :description %>
<br/>
<%= f.label :price %>
<%= f.text_area  :price %>
<br/>
<%= f.collection_select(:user_id, User.all, :id, :username) %>
<br/>
<%= f.submit %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/delete.html.erb
<h1>Products#delete</h1>
<p>Find me in app/views/products/delete.html.erb</p>

app/views/products/edit.html.erb
<h2> Ürün Düzenle </h2>
<%= form_for :product, {url: product_path(@product.id), method: :put} do |f| %>
    <%= render 'form', f:f %>
<% end %>

app/views/products/index.html.erb
<h1> Ürün Listesi </h1><h5><%= link_to 'Yeni ürün ekle', new_product_path %></h5>
<hr>
<% @products.each do |product| %>
    <h3>Ürün adı: <%= product.title %></h3><br/>
    <p>Açıklama:: <%= product.description %></p><br/>
    <p>Ücret: <%= product.price %></p><br/>
    <p>KDV Dahil: <%= product.vat_included_price %></p><br/>
    <p>Kullanıcı: <%= product.user.username %></p>
    <%= link_to 'Edit', edit_product_path(product)%>
    <%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: "Emin misin bak"} %>
    <hr>
<% end %>

app/views/products/new.html.erb
<h2> Yeni Ürün </h2>
<%= form_for :product, url: products_path do |f| %>
    <%= render 'form', f:f %>
<% end %>

app/views/products/show.html.erb
<h3>Ürün Adı: <%= @product.title %></h3><br/>
<p>Açıklama: <%= @product.description %></p><br/>
<p>Ücret: <%= @product.price %></p><br/>
<p>KDV Dahil: <%= @product.vat_included_price %></p><br/>
<p>Kullanıcı: <%= @product.user.username %></p><br/>
<%= link_to 'Ürün listesine dön', products_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <%= msg %><br/>
    <% end  %>
<% end %>
<div class="form-group">
  <%= f.text_field :username  %>
</div>
<div class="form-group">
  <%= f.text_field  :email %>
</div>
<div class="form-group">
  <%= f.text_field  :city %>
</div>
<div class="form-group">
  <%= f.text_field  :age %>
</div>
<%= f.submit %>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h2> Kullanıcı Düzenle </h2>
<%= form_for :user, {url: user_path(@user.id), method: :put} do |f| %>
    <%= render 'form', f:f %>
<% end %>

app/views/users/index.html.erb
<h1> Kullanıcı Listesi </h1><h5><%= link_to 'Yeni kullanıcı ekle', new_user_path %></h5>
<hr>
<% @users.each do |user| %>
    <h3>Kullanıcı Adı: <%= user.username %></h3><br/>
    <p>Email: <%= user.email %></p><br/>
    <p>Şehir: <%= user.city %></p><br/>
    <h3>Yaş: <%= user.age %></h3><br/>
    <h3>Ürünler: <%= user.products.map {|p| p.title}.join(', ') %></h3>
    <%= link_to 'Show', user_path(user) %>
    <%= link_to 'Edit', edit_user_path(user)%>
    <hr>
<% end %>

app/views/users/new.html.erb
<h2> Yeni Kullanıcı </h2>
<%= form_for :user, url: users_path do |f| %>
    <%= render 'form',f:f %>
<% end %>

app/views/users/show.html.erb
<h3>Kullanıcı Adı: <%= @user.username %></h3><br/>
<p>Email: <%= @user.email %></p><br/>
<p>City: <%= @user.city %></p><br/>
<h3>Yaş: <%= @user.age %></h3><br/>
<h3>Ürünler: <%= @user.products.map {|p| p.title}.join(',') %></h3>
<%= link_to 'Kullanıcı listesine dön', users_path %>